version: "2"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    ports:
      - "5000:5000"
      - "5001:5001"
  
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      # MYSQL_DATABASE: "video_to_text"
      # MYSQL_DATABASE_USER: "root"
    # volumes:
    #   # - ./db:/docker-entrypoint-initdb.d/:ro
    #   - ./static:/app:ro
    # secrets:
    # - $HOME/.token:/root/.token:400


