pipeline{
    agent any

    environment{
        DOCKERHUB_USERNAME="${DOCKERHUB_USERNAME}"
        DOCKERHUB_PASSWORD="${DOCKERHUB_PASSWORD}"
        DOCKERHUB_REPO= "video-to-text"
    }
    stages{
        stage('Build Docker Image'){
            steps{
                sh 'docker build -t ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}:${BUILD_NUMBER} .'
            }
        }
        stage('Test'){
            steps{
                sh 'winpty docker run -it ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}:${BUILD_NUMBER} /bin/bash'
            }
        }
        stage('Deploy'){
            steps{
                sh 'docker push ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}:${BUILD_NUMBER}'
            }
        }

        stage('Destroy Docker Container'){
            steps{
                sh 'docker rm $(docker ps -a -q)'
            }
        }
    
        stage('Deploy to Kubernetes'){
            steps{
                sh 'kubectl apply -f k8s'
            }
        }
    }
}