pipeline{
    agent any{
        label "master"
    }
    environment{
        DOCKERHUB_USERNAME="${DOCKERHUB_USERNAME}"
        DOCKERHUB_PASSWORD="${DOCKERHUB_PASSWORD}"
        DOCKERHUB_REPO= "video-to-text"
    }
    stages{
        stage('Build Docker Image'){
            steps{
                sh 'docker build -t ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}:${BUILD_NUMBER} .'
            }
        }
        stage('Test'){
            steps{
                sh 'docker run -it ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}:${BUILD_NUMBER} /bin/bash'
            }
        }
        stage('Deploy to Kubernetes'){
            steps{
                sh 'kubectl apply -f k8s'
            }
        }
    }
}